### ISSUE TITLE
API link in readme no longer works

### ISSUE THREAD

**Issue by varyamereon** [ryanbateman/bvg-sensor#1]
It seems the URL in the readme file detailing how to obtain the stop_id is out of date and no longer works. I have also tried https://v5.bvg.transport.rest/stations/nearby?latitude=52.52725&longitude=13.4123 however this also returns an error.

Thanks

**Comment by cvbraeuer** [comment]
deriving from https://petstore.swagger.io/?url=https%3A%2F%2Fv5.bvg.transport.rest%2F.well-known%2Fservice-desc%0A#/

the URL you are looking for should be something along the lines of 

https://v5.bvg.transport.rest/stops/nearby?latitude=52.52725&longitude=13.4123

**Comment by ryanbateman** [comment]
I've amended the docs to reflect this. Thanks, @cvbraeuer, for hunting down the fix, and thank you @varyamereon for raising the issue!
