### ISSUE TITLE
Integration 'bvgsensor' not found

### ISSUE THREAD

**Issue by varyamereon** [ryanbateman/bvg-sensor#2]
Having added a new sensor to my YAML file I get the error:

`Platform error sensor.bvgsensor - Integration 'bvgsensor' not found.`

Is this name correct or has it been renamed?

**Comment by cvbraeuer** [comment]
It seems the integration was renamed to "bvg_berlin_public_transport"

**Comment by ryanbateman** [comment]
Ah, good spot. I'll amend the docs. Thanks for raising the issue!
